version: "2.3" # optional since v1.27.0
services:
  db:
    image: postgres:13
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 9002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change-in-production
      - POSTGRES_DB=test_db
  minio:
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    volumes:
      - minio_vol:/minio_vol
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=test
      - MINIO_ROOT_PASSWORD=change-in-production
    command: server /minio_vol
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=compose
    depends_on:
      - db
    ports:
      - 3001:3001
volumes:
  db_vol: null
  minio_vol: null
